[project]
name = "aeros-navigation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "dronekit>=2.9.2",
    "gymnasium",
    "matplotlib",
    "mavsdk",
    "numpy",
    "opencv-python",
    "pymavlink>=2.4.49",
    "stable-baselines3",
    "torch",
    "ultralytics",
]

[tool.setuptools.packages.find]
include = ["control*", "missions*", "vision*", "rl*", "sim*", "training*"]
